---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*.md"
  templates:
  - project
- type: directory
  path: journal
  label: Journal
  create: documents
  match: "**/*.md"
  templates:
  - journal
- type: document
  path: data/theme.json
  label: Theme config
upload_dir: static/uploads
public_path: "/static/uploads"
front_matter_path: "../static/uploads"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: gridsome build
  output_directory: dist
